'use server'
import { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } from "@google/generative-ai";

const TAVILY_API_KEY = process.env.NEXT_PUBLIC_TAVILY_API_KEY;
const GEMINI_API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
const TAVILY_API_URL = "https://api.tavily.com/search";
const SEARCH_QUERY = "latest quantum computing technology news OR breakthroughs OR research";
const MAX_RESULTS_TAVILY = 7; // How many results to request from Tavily
const MAX_RESULTS_TO_PROCESS = 5; // How many results to actually process with Gemini (saves API calls)
const GEMINI_MODEL_NAME = process.env.NEXT_PUBLIC_LLM; // Or choose another suitable model

// --- Interfaces (optional but good practice) ---
interface TavilyResult {
    title: string;
    url: string;
    content: string; // Tavily often provides a snippet/content
    score: number;
    raw_content?: string; // Might be available depending on request
}

interface TavilyResponse {
    query: string;
    follow_up_questions: string[] | null;
    answer: string | null;
    images: string[] | null;
    results: TavilyResult[];
    response_time: number;
}

interface NewsItem {
    title: string;
    url: string;
    summary: string; // Summary generated by Gemini
    source: string; // e.g., domain name
}

// --- Helper Function to Extract Domain ---
function getDomainName(url: string): string {
    try {
        const parsedUrl = new URL(url);
        return parsedUrl.hostname.replace(/^www\./, ''); // Remove 'www.'
    } catch {
        console.warn(`Invalid URL encountered: ${url}`);
        return 'Unknown Source';
    }
}

// --- Main Data Fetching Function ---
async function fetchQuantumNews(): Promise<NewsItem[] | { error: string }> {
    if (!TAVILY_API_KEY || !GEMINI_API_KEY) {
        console.error("API keys for Tavily or Gemini are missing.");
        return { error: "Server configuration error: API keys missing." };
    }

    // --- Step 1: Fetch search results from Tavily ---
    let tavilyResults: TavilyResult[] = [];
    try {
        console.log(`Fetching news from Tavily with query: "${SEARCH_QUERY}"`);
        const response = await fetch(TAVILY_API_URL, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                api_key: TAVILY_API_KEY,
                query: SEARCH_QUERY,
                search_depth: "basic", // 'basic' or 'advanced'
                include_answer: false, // We don't need Tavily's combined answer
                include_images: false,
                include_raw_content: false, // We'll let Gemini summarize from URL
                max_results: MAX_RESULTS_TAVILY,
                include_domains: [],
                exclude_domains: [],
            }),
            cache: 'no-store', // Ensure fresh results, adjust if needed
        });

        if (!response.ok) {
            const errorBody = await response.text();
            console.error(`Tavily API error (${response.status}): ${errorBody}`);
            throw new Error(`Tavily API request failed with status ${response.status}`);
        }

        const data: TavilyResponse = await response.json();
        tavilyResults = data.results || [];
        console.log(`Received ${tavilyResults.length} results from Tavily.`);

    } catch (error: unknown) {
        console.error("Error fetching from Tavily:", error);
        const errorMessage = error instanceof Error ? error.message : 'Unknown error.';
        return { error: `Failed to fetch news from search provider. ${errorMessage}` };
    }

    if (tavilyResults.length === 0) {
        console.log("No relevant news found by Tavily.");
        return []; // Return empty array if no results
    }

    // --- Step 2: Initialize Gemini Client ---
    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: GEMINI_MODEL_NAME || "gemini-1.5-flash" });

    const generationConfig = {
        temperature: 0.7, // Adjust creativity vs. factuality
        topK: 1,
        topP: 1,
        maxOutputTokens: 100, // Limit summary length
    };

    // Safety settings to prevent harmful content generation
    const safetySettings = [
        { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
        { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
        { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
        { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    ];

    // --- Step 3: Summarize relevant results with Gemini ---
    const summarizedNews: NewsItem[] = [];
    // Limit the number of results processed to avoid excessive API calls
    const resultsToProcess = tavilyResults.slice(0, MAX_RESULTS_TO_PROCESS);

    console.log(`Attempting to summarize top ${resultsToProcess.length} results with Gemini...`);

    for (const result of resultsToProcess) {
        if (!result.url || !result.title) {
            console.warn("Skipping result due to missing URL or Title:", result);
            continue;
        }

        // Construct the prompt for Gemini
        // Providing context (title, snippet) helps Gemini focus.
        const prompt = `You are an assistant for "Superpos", an educational quantum computing platform.
        Please provide a concise (1-2 sentences) summary of the key quantum technology point from the following article.
        Focus on the educational value for someone learning quantum computing.
        Article Title: "${result.title}"
        Article URL: ${result.url}
        ${result.content ? `\nInitial Context Snippet: "${result.content}"` : ''}

        Summary:`;

        try {
            console.log(`  - Requesting summary for: ${result.url}`);
            const geminiResult = await model.generateContent({
                contents: [{ role: "user", parts: [{ text: prompt }] }],
                generationConfig,
                safetySettings,
            });

            // Check for blocked content or missing response
            if (!geminiResult.response ||
                !geminiResult.response.candidates ||
                geminiResult.response.candidates.length === 0 ||
                !geminiResult.response.candidates[0].content) {

                const blockReason = geminiResult.response?.promptFeedback?.blockReason;
                console.warn(`Gemini failed to generate content for ${result.url}. Reason: ${blockReason || 'No candidate content'}`);

                // Fallback: Use Tavily's content if Gemini fails, or a placeholder
                summarizedNews.push({
                    title: result.title,
                    url: result.url,
                    summary: result.content || "Summary could not be generated for this article.",
                    source: getDomainName(result.url),
                });
                continue; // Skip to next result
            }

            const summary = geminiResult.response?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "Summary could not be generated.";
            console.log(`  - Summary received for: ${result.url}`);

            summarizedNews.push({
                title: result.title,
                url: result.url,
                summary: summary || "Summary generated was empty.", // Handle empty summary case
                source: getDomainName(result.url),
            });

            // Optional: Add a small delay between API calls to avoid rate limiting
            await new Promise(resolve => setTimeout(resolve, 200)); // 200ms delay

        } catch (error: unknown) {
            console.error(`Error summarizing ${result.url} with Gemini:`, error);

            const errorMessage = error instanceof Error ? error.message : 'Unknown error.';
            // Optional: Add item with error message or skip
            summarizedNews.push({
                title: result.title,
                url: result.url,
                summary: `Could not generate summary. ${errorMessage}`,
                source: getDomainName(result.url),
            });
        }
    }

    console.log(`Successfully summarized ${summarizedNews.filter(n => !n.summary.startsWith('Could not')).length} news items.`);
    return summarizedNews;
}
export async function getLatestBriefings(): Promise<{ success: true; data: NewsItem[] } | { success: false; error: string }> {
    try {
        const news = await fetchQuantumNews();
        if ('error' in news) {
            return { success: false, error: news.error as string };
        }
        return { success: true, data: news as NewsItem[] };
    } catch {
        return { success: false, error: "SIGNAL_INTERFERENCE: Could not establish connection." };
    }
}